# Site settings

author: Lambda
email: example@email.com
twitter_username: twitter
github_username:  github
googleplus_username: google

title: Lambda's blog

baseurl: "/blog"    # the subpath of your site
url: ""

description: "I know that what I'm doing looks stupid, but I'm a big boy and really want to do this."

favo: "春梦随云散，飞花逐水流"
descrpt: "“巧者劳而智者忧，无能者无所求，饱食而遨游，泛若不系之舟”  ——《南华经》"

#
# Build settings
#

markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "superscript", "highlight", "footnotes", "tables", "underline"]  # "with_toc_data"

#kramdown:
#  input: GFM

#highlighter: pygments
highlighter: rouge

sass:
    style: compressed

permalink: /posts/:categories/:title.html

paginate: 7
#paginate_path: 'page/:num'

gems: [jekyll-paginate]

# disqus comment
disqus_url: <...>     # Your unique disqus url; Eg: `hello.disqus.com`; set `none` mean disable disqus comment.


#
# commentted option
#

#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt
